# Generated by Django 2.2.6 on 2019-12-16 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Patients_Heart_Model', '0002_patient_classified_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_classified',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
