# Generated by Django 2.2.6 on 2020-02-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients_Heart_Model', '0003_auto_20191216_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FamilyName', models.CharField(max_length=100)),
            ],
        ),
    ]
