# Generated by Django 2.2.6 on 2020-02-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients_Heart_Model', '0004_family_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Family_Member',
            new_name='Family',
        ),
    ]
