# Generated by Django 2.2.6 on 2020-02-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients_Heart_Model', '0005_auto_20200210_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='members',
            field=models.ManyToManyField(to='Patients_Heart_Model.Patient_Classified', verbose_name='member'),
        ),
    ]
