# Generated by Django 2.2.6 on 2020-02-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients_Heart_Model', '0006_family_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='FamilyName',
            field=models.CharField(max_length=100, verbose_name='familyname'),
        ),
    ]
