# Generated by Django 2.2.6 on 2019-11-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patients_Heart_Model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_basic_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True, null=True)),
                ('Patient_age', models.IntegerField(max_length=10)),
                ('Current_Smoker', models.BooleanField(default=False)),
                ('CigsPerDay', models.IntegerField(max_length=10)),
                ('BPMeds', models.BooleanField()),
                ('PrevalentStroke', models.IntegerField(max_length=10)),
                ('PrevalentHyp', models.IntegerField(max_length=10)),
                ('diabetes', models.BooleanField()),
                ('totChol', models.IntegerField(max_length=10)),
                ('sysBP', models.IntegerField(max_length=10)),
                ('diaBP', models.IntegerField(max_length=10)),
                ('BMI', models.FloatField(max_length=10)),
                ('heartRate', models.IntegerField(max_length=10)),
                ('glucose', models.IntegerField(max_length=10)),
                ('TenYearCHD', models.BooleanField(null=True)),
                ('Patient_ID', models.ManyToManyField(null=True, to='Patients_Heart_Model.Patient_Classified')),
            ],
            options={
                'ordering': ['date_sent'],
            },
        ),
    ]
