# Generated by Django 2.2.6 on 2019-11-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients_Records', '0002_auto_20191127_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_basic_record',
            name='TenYearCHD',
            field=models.NullBooleanField(default=None),
        ),
    ]
