# Generated by Django 2.2.6 on 2019-11-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients_Records', '0003_auto_20191127_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_basic_record',
            name='TenYearCHD',
            field=models.NullBooleanField(),
        ),
    ]
