# Generated by Django 2.2.6 on 2019-12-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients_Records', '0004_auto_20191127_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_basic_record',
            name='Patient_ID',
            field=models.ManyToManyField(related_name='patient', to='Patients_Heart_Model.Patient_Classified'),
        ),
    ]
