# Generated by Django 2.2.6 on 2020-02-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content_Management', '0003_article_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
