# Generated by Django 2.2.6 on 2020-02-19 11:09

from django.db import migrations, models
import hitcount.views
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('Content_Management', '0005_article_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            bases=(models.Model, hitcount.views.HitCountMixin),
        ),
    ]
