# Generated by Django 2.2.6 on 2020-02-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content_Management', '0007_auto_20200219_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='title',
            new_name='Title',
        ),
    ]
