# Generated by Django 2.2.6 on 2020-02-10 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=120)),
                ('fat', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('protein', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('reaction', models.IntegerField(choices=[(1, 'Sad'), (2, 'Slightly Sad'), (3, 'Nutral'), (4, 'Slightly Happy'), (5, 'Happy')], default=3, max_length=100)),
                ('breakfast', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakfast', to='dailydiet.Meal')),
                ('dinner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dinner', to='dailydiet.Meal')),
                ('lunch', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch', to='dailydiet.Meal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diet_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
